I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 49, in script
    Zeil "For more effects, you can check out Ren'Py's guides."
Exception: Sayer 'Zeil' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 49, in script
    Zeil "For more effects, you can check out Ren'Py's guides."
  File "D:\!Projects\3. Game and Digital\renpy-8.0.0-sdk\renpy\ast.py", line 861, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\!Projects\3. Game and Digital\renpy-8.0.0-sdk\renpy\ast.py", line 754, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Zeil' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
trial 1 1.0
Tue Jul 19 21:01:42 2022
